- name: Install and Configure Dockerized Redis Server
  hosts: all
  become: true
  become_method: sudo
  tasks:
      - name: update nameserver to support various installations online
        lineinfile:
          path: /etc/resolv.conf
          line: 'nameserver 8.8.8.8'
          state: present
      - name: Install packages
        apt: 
          update_cache: yes 
          name: "{{ packages }}" 
          state: present
        vars:
          packages:
          - git
          - python-pip
          - curl
      - name: install docker
        shell: curl -sSL https://get.docker.com/ | sh
        args:
          creates: /usr/bin/docker
      - name: install docker-py module
        pip: name=docker
      - name: install docker-compose module
        pip: name=docker-compose
      - name: Start docker daemon
        service: name=docker state=started enabled=yes
      - name: Create a Redis docker container
        docker_container:
          name: redis
          image: redis:alpine
          ports:
            - "6379:6379"
          state: started
      
