- name: Install and Configure Dockerized lamp stack with a simple test application
  hosts: all
  become: true
  become_method: sudo
  vars:
      repository_url: https://bitbucket.org/azneita/devops-challenge.git
      repository_path: /webapps/devops
      project_name: devops-code-challenge
  tasks:
      - name: 
        lineinfile:
          path: /etc/resolv.conf
          line: 'nameserver 8.8.8.8'
          state: present
      - name: Install packages
        apt: 
          update_cache: yes 
          name: "{{ packages }}" 
          state: present
        vars:
          packages:
          - git
          - python-pip
          - curl
      - name: install docker
        shell: curl -sSL https://get.docker.com/ | sh
        args:
          creates: /usr/bin/docker
      - name: install docker-py module
        pip: name=docker
      - name: install docker-compose module
        pip: name=docker-compose
      - name: Start docker daemon
        service: name=docker state=started enabled=yes
      - docker_service:
           project_src: /vagrant/server1
           state: present

