- name: Install and Configure Dockerized lamp stack with a simple test application
  hosts: all
  become: true
  become_method: sudo
  tasks:
      - name: update nameserver to avoid issues during various online installations
        lineinfile:
          path: /etc/resolv.conf
          line: 'nameserver 8.8.8.8'
          state: present
      - name: Install packages
        apt: 
          update_cache: yes 
          name: "{{ packages }}" 
          state: present
        vars:
          packages:
          - git
          - python-pip
          - curl
          - redis-tools
      - name: install docker
        shell: curl -sSL https://get.docker.com/ | sh
        args:
          creates: /usr/bin/docker
      - name: install docker-py module
        pip: name=docker
      - name: install docker-compose module
        pip: name=docker-compose
      - name: Start docker daemon
        service: name=docker state=started enabled=yes
      - name: pull php docker image
        docker_image:
           name: php:7.1-fpm-alpine
           state: present
      - name: pull mysql image
        docker_image:
           name: mysql/mysql-server:5.7
           state: present
      - name: pull apache image
        docker_image:
           name: httpd:2.4-alpine
      - name: create lamp stack containers using the docker_compose.yml file present in the ./server1 directory
        docker_service:
           project_src: /vagrant/server1
           state: present

